version: "2.1"
services:
  task-checker:
    build: .
    expose:
      - "18602"
      - "9000"
    command: celery -A checker.checker_producer beat
  worker-checker:
    build: .
    command: celery -A checker.checker_producer worker
    expose:
      - "18602"
      - "18604"
      - "80"
      - "9000"
  consumer-checker:
    build: .
    expose:
      - "9000"
      - "18602"
      - "18604"
    environment:
      - PYTHONPATH=/usr/src/app
    command: python checker/chekcer_consumer.py